<a href="https://colab.research.google.com/github/AhmadNass7/teaching/blob/main/Active_Learning_New_continue_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import random
import numpy as np
import pandas as pd
import sklearn.metrics
import sklearn.ensemble
import sklearn.neighbors
import sklearn.model_selection
import plotly.graph_objects as an

In [11]:
df= pd.read_csv("mnist.csv")
df= df.set_index("id")
df.head(3)

,class,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
id,,,,,,,,,,,,,,,,,,,,,
31953,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34452,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60897,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
x= df.drop(["class"], axis=1)
y= df["class"]
x_train , x_test ,y_train, y_test = sklearn.model_selection.train_test_split(x,y)

In [13]:
labeling_budget= 30

In [14]:
number_of_labels_random_sampling= []
accuraciews_random_sampling= []
sampled_indexes= []

for i in range(labeling_budget):

  # sampling training data points
  unlabeled_x_train= x_train.drop(sampled_indexes)
  sampled_indexes+= random.sample(list(unlabeled_x_train.index),1)


  # updating the labeled training set
  labeled_x_train= x_train.loc[sampled_indexes, :]
  labeled_y_train= y_train.loc[sampled_indexes]


  # train and test the model

  model= sklearn.neighbors.KNeighborsClassifier(n_neighbors=1)
  model.fit(labeled_x_train, labeled_y_train)
  y_predicted= model.predict(x_test)
  accuracy= sklearn.metrics.accuracy_score(y_test, y_predicted)

  # save the results
  number_of_labels_random_sampling.append(len(sampled_indexes))
  accuracies_random_sampling.append(accuracy)

  pd.DataFrame({"Number of Labels": number_of_labels_random_sampling, "Accuracy":accuracies_random_sampling})

NameError: ignored